# Site settings
title: "2VStudio"
email: gahejny@2vstudio.com
description:  > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.2vstudio.com" # the base hostname & protocol for your site

linkedin_username: gingerhoward
facebook_username: GingerHowardViolinViolaStudio

# Build settings
markdown: kramdown
